### PR TITLE
Fix FAT32 scheme-specific type

### PR DESCRIPTION
**Pull request by jlduran**

### CODE REVIEW

**Comment by asomers** [comment]
Do you have a reference?

**Comment by jlduran** [comment]
https://github.com/freebsd/freebsd/blob/47aa838516f2954372f66cf72bd285aa4c070ac8/release/tools/arm.subr#L68

**Comment by asomers** [comment]
That's not a reference, just an example use.  A reference would be the gpart code that handles partition types, or better yet the FAT standard (is there one?) or the GPT standard, if relevant.

**Comment by jlduran** [comment]
My bad, `0x0B` is the right file system type:

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb457122(v=technet.10)

**Comment by jlduran** [comment]
Wonder if after https://reviews.freebsd.org/D15266 I should fix and re-submit the PR.

**Pull request closed without merging**
