### PR TITLE
add Winbond w25x64 support

### PR DESCRIPTION
**Pull request by epipenau**
Tested and working support for the Winbond w25x64 flash.

### CODE REVIEW

**Comment by epipenau** [comment]
Support for the Ubiquiti Rocket M2 and M5.  This may also work with other M series products.

**Comment by epipenau** [comment]
added universal kernel and rootfs mtd partition sizing detection to the ROCKET_M2HP.hints file

**Comment by erikarn** [comment]
committed the flash change in r300704.

**Comment by bsdimp** [comment]
Committed the rest....

**Pull request closed without merging**
