### PR TITLE
WD and WDC added as supported vendors to camcontrols fwupdate

### PR DESCRIPTION
**Pull request by JacobBurley**
Camcontrol only supported HGST branded drives, I updated the vendors list to support WDC and WD branded drives to improve compatibility for future drive releases

### CODE REVIEW

**Comment by seanbruno** [comment]
@JacobBurley I can commit this, but I don't know that fwupdate has been tested on any WD disks.  Did you test this and did it work for you?  Can you post the disk model in use and maybe the output of a succesfull update to one of the drives?

**Comment by JacobBurley** [comment]
Yes I have tested this on several WD disks, and sure I can post output the success of a few different tests

**Comment by JacobBurley** [comment]
`root@BSD:/usr/home/Jacob # /usr/obj/usr/home/Jacob/freeBSD/amd64.amd64/sbin/camcontrol/camcontrol devlist
<WDC WUSTR1596ASS200 A900>         at scbus0 target 103 lun 0 (da1,pass4)
<HGST HMH7210A0AL4600 a0GA>        at scbus0 target 106 lun 0 (pass0,da0)
<HGST HUS722T2TALA604 RAGNWA09>    at scbus2 target 0 lun 0 (pass1,ada0)
<HGST HUS722T2TALA604 RAGNWA04>    at scbus3 target 0 lun 0 (pass2,ada1)
<AHCI SGPIO Enclosure 1.00 0001>   at scbus4 target 0 lun 0 (ses0,pass3)
root@BSD:/usr/home/Jacob # /usr/obj/usr/home/Jacob/freeBSD/amd64.amd64/sbin/camcontrol/camcontrol fwdownload pass4 -f BPGNA925.bin 
You are about to download firmware image (BPGNA925.bin) into the following device:
pass4: <WDC WUSTR1596ASS200 A900> Fixed Direct Access SPC-5 SCSI device
pass4: Serial Number         WVV05D1A
pass4: 600.000MB/s transfers, Command Queueing Enabled
Using a timeout of 50000 ms, which is the default.

It may damage your drive. Are you SURE you want to do this? (yes/no) yes
BPGNA925.bin 100% |**********************************************************************************************************************************************************|  2512 KiB   1.22 MiB/s    00:00 ETA
Firmware download successful
root@BSD:/usr/home/Jacob # /usr/obj/usr/home/Jacob/freeBSD/amd64.amd64/sbin/camcontrol/camcontrol devlist
<WDC WUSTR1596ASS200 A900>         at scbus0 target 103 lun 0 (da1,pass4)
<HGST HMH7210A0AL4600 a0GA>        at scbus0 target 106 lun 0 (pass0,da0)
<HGST HUS722T2TALA604 RAGNWA09>    at scbus2 target 0 lun 0 (pass1,ada0)
<HGST HUS722T2TALA604 RAGNWA04>    at scbus3 target 0 lun 0 (pass2,ada1)
<AHCI SGPIO Enclosure 1.00 0001>   at scbus4 target 0 lun 0 (ses0,pass3)
root@BSD:/usr/home/Jacob # /usr/obj/usr/home/Jacob/freeBSD/amd64.amd64/sbin/camcontrol/camcontrol fwdownload pass4 -f BPGNA900.bin 
You are about to download firmware image (BPGNA900.bin) into the following device:
pass4: <WDC WUSTR1596ASS200 A925> Fixed Direct Access SPC-5 SCSI device
pass4: Serial Number         WVV05D1A
pass4: 600.000MB/s transfers, Command Queueing Enabled
Using a timeout of 50000 ms, which is the default.

It may damage your drive. Are you SURE you want to do this? (yes/no) yes
BPGNA900.bin 100% |**********************************************************************************************************************************************************|  2512 KiB   1.22 MiB/s    00:00 ETA
Firmware download successful
root@BSD:/usr/home/Jacob # 

`

**Comment by JacobBurley** [comment]
I am using a bare cove model WDC solid state drive, you can see in the above output that the firmware was flashed between two different revisions. I would like to provide more data, however, I do not have a lot of drive firmware readily available

**Comment by JacobBurley** [comment]
Hi @seanbruno 
Can you please accept this pull request?  We have WDC customers waiting on this change and it's holding up their ability to update FW.

**Comment by bsdimp** [comment]
this is on my list of things to merge soon

**Comment by bsdimp** [comment]
But I was holding off: what problem does this solve?

**Comment by JacobBurley** [comment]
A customer wants to update drive firmware on freeBSD servers, and different model drives are officially from one of three vendors that are all under the western digital name, so adding WD and WDC as vendors allowed for successful firmware updating on our newer model drives, in addition to our legacy drives which are branded as HGST

**Comment by JacobBurley** [comment]
Hello, @bsdimp @seanbruno, I really need this merged soon, I know that it is not a top priority, but it would really help are customers.

Thank you

**Comment by bsdimp** [comment]
r345364 should do the trick. It's slightly different (I didn't define new VENDOR_xxx values), but should be good. Please confirm and I'll MFC after a couple of days even though I forgot to tag it as such. Thanks for answering the questions I had about it. I know that can be a bit of a pain sometimes.

**Comment by bsdimp** [comment]
Thanks for the reminder. It worked its way almost to the top of my queue,
but I got distracted. Merging now.

Warner

**Comment by cemeyer** [comment]
Can this be closed as resolved?

**Comment by emaste** [comment]
Warner committed modified version in https://github.com/freebsd/freebsd/commit/e1eaa7c203a9353d513a0b26eafb22d507c0aab4

Thank you for the submission!

**Pull request closed without merging**
