### PR TITLE
off is zero. It can be removed.

### PR DESCRIPTION
**Pull request by Wuyang-Chung**
off = trunc_page(offset + filsz) - trunc_page(offset + filsz) and it is zero.

### CODE REVIEW

**Comment by markjdb** [comment]
I committed the removal of `off`, thanks. It's not obvious to me that the compiler won't perform the micro-optimization in the other commit; did you verify that we get some change in the compiled kernel?

**Comment by Wuyang-Chung** [comment]
I write a small test program and compare the assembly output for both statements. I didn't expect that the compiler can optimize the code as efficient as the original one. The compiler is really doing a good job.

**Comment by emaste** [comment]
> The compiler is really doing a good job.

Indeed, the compiler can do some quite interesting optimizations.

> The proposed one is more easy for me to understand the code. :)

This is key, we should aim for readability/understandability - especially when the compiler generates the same code either way. I'm not sure which I find more understandable though; I read the current code as "excluding the already copied portion" and your proposed change as "the partial page content"

**Comment by Wuyang-Chung** [comment]
On a second thought the original one is better. :)

**Pull request closed without merging**
