### PR TITLE
Update user.subr

### PR DESCRIPTION
**Pull request by oleantus**
Adding the ability to copy from the skel directory not only individual .dot files, but also directories containing files such as KDE directory with configuration files.

### CODE REVIEW

**Comment by emaste** [comment]
Paging @allanjude @devinteske

**Comment by allanjude** [comment]
Are the files in the subdirectory going to be named 'dot.foo' ?
If so, we'll need to loop over those separately, to remove the 'dot' part.

I am not sure what the expected behaviour is here.

**Comment by oleantus** [comment]
> Are the files in the subdirectory going to be named 'dot.foo' ?

Yes.

> If so, we'll need to loop over those separately, to remove the 'dot' part.

Don't need this.

I am developer of ulbsd.ru (freebsd clone). I am tested this in our product. It's worked!

**Comment by emaste** [comment]
I don't like the inconsistency of renaming skel's dot.foo files to .foo, but not files in subdirectories. That said, I think we should probably just move away from the "dot" prefix in skel, rather than extending this change to rename files in subdirectories too.

**Comment by oleantus** [comment]
> I think we should probably just move away from the "dot" prefix in skel, rather than extending this change to rename files in subdirectories too.

It is a good idea. But now this patch solves the problem with the subdirectories in the skel directory.

**Comment by yaneurabeya** [comment]
I like this change.

As far as moving away from `dot.` prefixed paths, I think that there's a lot more work that would be required to make this a reality, and there might be unnecessary breakage due to shifting away from `dot.` prefixing.

**Comment by bsdimp** [comment]
I'll commit this patch as is. Most .foo/bar setups don't have .foo/.bar, so the need for dot.bar is much reduced.

**Comment by yaneurabeya** [comment]
@bsdimp: please check with @devinteske

**Comment by devinteske** [comment]
Reviewing

**Comment by devinteske** [comment]
As discussed on IRC with imp, Allan Jude, John Baldwin, and myself...

bsdconfig mirrors the actions of pw(8) with respect to skel (please see the pw(8) manual with respect to skeleton files and the effect the `-m' parameter has on copying of skel files).

At the very least, the suggested change here has to be accompanied by a corresponding change to several other tools, including but not limited to pw(8), adduser(8), and their respective manuals.

**Comment by bsdimp** [comment]
Redirected to bugzilla. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217602

**Pull request closed without merging**
