### PR TITLE
Patch to enable correct sound output on jack plug on DellXPS9560

### PR DESCRIPTION
**Pull request by kstaring**
The Dell XPS 9560 laptop has a jack plug, but no sound can be heard if one plugs in earbuds. However, if one slightly disconnects the jack plug, distorted sound can be heard.
It looks like the Dell has some crazy pin configuration, or there's a problem that both inputs and outputs are enabled when the jack plug detection signals a jack plug insertion?
Anyway, porting the Linux patch to FreeBSD fixed the problem.

Excuse the magic numbers in the patch...

### CODE REVIEW

**Comment by seanbruno** [comment]
I've committed this to freebsd at svn r332890

**Comment by kstaring** [comment]
Thanks!
There're a lot of these kinds of patches in the Linux driver not present in FreeBSD. Would it be useful to port most if not all of them over, or wait for reports and fix them case by case?

**Comment by seanbruno** [comment]
If you are game to start generating patches, I'm game to start committing them.  Let me know what you want to do.

**Comment by emaste** [comment]
I agree, the closer we can get to having FreeBSD fully "just work" on arbitrary laptops, the better.

**Comment by seanbruno** [comment]
How about we start with the audio devices that we all have lying around.

Currently, I use the following daily:```

hdac0@pci0:0:31:3:      class=0x040300 card=0x20648086 chip=0xa1708086 rev=0x31 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-H HD Audio'
    class      = multimedia
    subclass   = HDA

hdac0@pci0:0:3:0:       class=0x040300 card=0x05ca1028 chip=0x0a0c8086 rev=0x0b 
hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Haswell-ULT HD Audio Controller'
    class      = multimedia
    subclass   = HDA
```

**Comment by kstaring** [comment]
@seanbruno Good idea, I'll have a look in the coming days. Can you tell what isn't working with sound in- or output?

**Comment by seanbruno** [comment]
On my laptop(Haswell), the headphone jack emits white noise and doesn't provide any useful audio playback.  Speakers are fine.

On the desktop (sunrise), there is a large "click" noise when the system powers up.

**Comment by kstaring** [comment]
@seanbruno Can you please check out [dell_latitude_e7240_jack_output_fix](https://github.com/kstaring/freebsd/tree/dell_latitude_e7240_jack_output_fix) and check if it's working on your laptop? Apparently the same pin configuration override as my XPS 9560 **might** fix the problem on your Latitude E7240 as well, but I'm not sure if this is the whole story, since the Linux driver has a bit more code that I can't relate to FreeBSD code at the moment.
As for the NUC, can you also show the output of /dev/sndstat? The pciconf output only shows hdac info, but the hdaa driver is equally important.

**Comment by kstaring** [comment]
Just a heads-up; I'm in the process of converting the Linux pin overrides for, as a start, the Realtek chipset. For starters, I'm converting the if/else if/[...] chain into a structure which can be looped over and edited a bit easier. [This](https://github.com/kstaring/freebsd/tree/hda_pin_fixes_realtek) is the branch to look out for.  I'll push some code in the coming days and will create a new pull request when it's ready.

**Comment by daniloegea** [comment]
Hi, thank you for your work. Same problem with low and noisy sound on headphones here.
I was trying the patches from the Linux's driver before find this issue here. No success though...

The audio card is identified as a Realtek ALC255 (Acer Aspire F 15 - F5-573G).

I've tried your work from github.com/kstaring/freebsd/tree/hda_pin_fixes_realtek but it's doesn't work as well.

hdac0@pci0:0:31:3:      class=0x040300 card=0x108f1025 chip=0x9d718086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP HD Audio'
    class      = multimedia
    subclass   = HDA

If you have any clue I appreciate.

Thanks!

**Comment by kstaring** [comment]
@daniloegea Does it work on linux? There are some fix entries on linux that I didn't port over, such as some vendor-specific fixes as opposed to machine-specific fixes. Thanks for the pciconf output though; it will make fixing easier. Btw, can you post your question in the hda_pin_fixes_realtek_alc255 pull request? (Since the fix, if I can find one, will be pushed there.)

**Comment by daniloegea** [comment]
On Linux it works flawlessly. I'll check this pull request. Thanks!

**Pull request closed without merging**
